#
# eChronos Real-Time Operating System
# Copyright (C) 2015  National ICT Australia Limited (NICTA), ABN 62 102 206 173.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3, provided that these additional
# terms apply under section 7:
#
#   No right, title or interest in or to any trade mark, service mark, logo or
#   trade name of of National ICT Australia Limited, ABN 62 102 206 173
#   ("NICTA") or its licensors is granted. Modified versions of the Program
#   must be plainly marked as such, and must not be distributed using
#   "eChronos" as a trade mark or product name, or misrepresented as being the
#   original Program.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @TAG(NICTA_AGPL)
#
version: 1.0.{build}
branches:
    except:
        - archive/*
        - abandoned/*
clone_depth: 1
environment:
    PATH: C:\splint-3.1.1\bin;C:\msys64\mingw64\bin;%PATH%;C:\Program Files\Git\cmd
    matrix:
        - PYVER: 3.5
        - PYVER: 3.4
        # Python 3.3 is no longer officially supported.
        # Therefore, the project also does not have to support it.
        # However, we still test against this version to learn when we break Python 3.3 support.
        - PYVER: 3.3
build_script:
    - pwd
    - curl -fsS -o splint-3.1.1.win32.zip http://www.splint.org/downloads/binaries/splint-3.1.1.win32.zip
    - powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('splint-3.1.1.win32.zip', 'C:\'); }"
    - del splint-3.1.1.win32.zip
test_script:
    - py -%PYVER% --version
    - git --version
    - gcc --version
    - splint --help

    - py -%PYVER% x.py test licenses
    - py -%PYVER% x.py test provenance
    - py -%PYVER% x.py test x
    - py -%PYVER% x.py test style
    - py -%PYVER% x.py test pystache
    - py -%PYVER% x.py test prj
    - REM py -%PYVER% x.py test units
    - py -%PYVER% x.py test systems
    - py -%PYVER% x.py build prj
    - py -%PYVER% x.py build packages

    - py -%PYVER% prj/app/prj.py build stub.acamar
    - py -%PYVER% prj/app/prj.py build stub.acrux
    - py -%PYVER% prj/app/prj.py build stub.gatria
    - py -%PYVER% prj/app/prj.py build stub.kochab
    - py -%PYVER% prj/app/prj.py build stub.kraz
    - py -%PYVER% prj/app/prj.py build stub.phact
    - py -%PYVER% prj/app/prj.py build stub.rigel

    - py -%PYVER% prj/app/prj.py analyze stub.acamar
    - py -%PYVER% prj/app/prj.py analyze stub.acrux
    - py -%PYVER% prj/app/prj.py analyze stub.gatria
    - py -%PYVER% prj/app/prj.py analyze stub.kochab
    - py -%PYVER% prj/app/prj.py analyze stub.kraz
    - py -%PYVER% prj/app/prj.py analyze stub.phact
    - py -%PYVER% prj/app/prj.py analyze stub.rigel

    - py -%PYVER% x.py build partials
    - py -%PYVER% x.py build docs
    - py -%PYVER% x.py build release
artifacts:
- path: packages\*\rtos-*\docs.pdf
  name: documentation
deploy: off
