version: 1.0.{build}
branches:
    except:
        - archive/*
        - abandoned/*
clone_depth: 1
environment:
    PATH: C:\splint-3.1.1\bin;C:\msys64\mingw64\bin;%PATH%;C:\Program Files\Git\cmd
build_script:
    - pwd
    - curl -fsS -o splint-3.1.1.win32.zip http://www.splint.org/downloads/binaries/splint-3.1.1.win32.zip
    - powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('splint-3.1.1.win32.zip', 'C:\'); }"
test_script:
    - py -3 --version
    - git --version
    - gcc --version
    - splint --help

    - py -3 x.py test licenses
    - py -3 x.py test provenance
    - py -3 x.py test x
    - py -3 x.py test style
    - py -3 x.py test pystache
    - py -3 x.py test prj
    - REM py -3 x.py test units
    - py -3 x.py test systems
    - py -3 x.py build prj
    - py -3 x.py build packages

    - py -3 prj/app/prj.py build stub.acamar
    - py -3 prj/app/prj.py build stub.acrux
    - py -3 prj/app/prj.py build stub.gatria
    - py -3 prj/app/prj.py build stub.kochab
    - py -3 prj/app/prj.py build stub.kraz
    - py -3 prj/app/prj.py build stub.phact
    - py -3 prj/app/prj.py build stub.rigel

    - py -3 prj/app/prj.py analyze stub.acamar
    - py -3 prj/app/prj.py analyze stub.acrux
    - py -3 prj/app/prj.py analyze stub.gatria
    - py -3 prj/app/prj.py analyze stub.kochab
    - py -3 prj/app/prj.py analyze stub.kraz
    - py -3 prj/app/prj.py analyze stub.phact
    - py -3 prj/app/prj.py analyze stub.rigel

    - py -3 x.py build partials
    - py -3 x.py build docs
    - py -3 x.py build release
artifacts:
- path: packages\*\rtos-*\docs.pdf
  name: documentation
deploy: off
